# Generated by Django 4.2 on 2025-10-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app", "0002_logitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="logitems",
            name="key_name",
            field=models.CharField(default="name", max_length=255),
        ),
    ]
