# Generated by Django 4.2 on 2025-10-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app", "0003_logitems_key_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_key", models.CharField(db_index=True, max_length=100)),
                ("ip_address", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=200)),
                ("status_code", models.IntegerField()),
                ("response_size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LogSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_key", models.CharField(db_index=True, max_length=100)),
                ("total_requests", models.IntegerField()),
                ("success_count", models.IntegerField()),
                ("client_error_count", models.IntegerField()),
                ("server_error_count", models.IntegerField()),
                ("top_endpoint", models.CharField(max_length=200)),
                ("top_ip", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
