# Generated by Django 4.2 on 2025-10-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app", "0004_logentry_logsummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_name", models.CharField(default="name", max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("blob_url", models.URLField()),
                ("line_number", models.IntegerField(default=0)),
                ("content", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
