# Generated by Django 4.2 on 2025-10-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app", "0005_rawitems"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rawitems",
            unique_together={("key_name", "file_name")},
        ),
    ]
