# Generated by Django 4.2 on 2025-10-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app", "0006_alter_rawitems_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rawitems",
            unique_together=set(),
        ),
    ]
